[build]
builder = "nixpacks"
buildCommand = "npm run build"
nixpacksVersion = "1.13.1"

[build.environment]
NODE_VERSION = "20.18.0"

[deploy]
startCommand = "node -r ./dist/crypto-polyfill.js dist/main"
healthcheckPath = "/api/health"
healthcheckTimeout = 120
initialDelay = 45

[[services]]
name = "web"
[[services.ports]]
port = 3000
http = true

[services.env]
NODE_ENV = "production"
NODE_VERSION = "20.18.0"

[services.scale]
min = 1
max = 2
memory = 1024